package com.soulsync.service;
import com.soulsync.domain.*; import com.soulsync.domain.Enums.*; import com.soulsync.exception.NotFoundException; import com.soulsync.repository.*; import com.soulsync.security.CurrentUser; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service @RequiredArgsConstructor
public class AdminService { private final UserRepository users; private final ProfileRepository profiles; private final ReportRepository reports; private final AuditLogRepository audits; private final CurrentUser current;
 public record AdminUserDto(UUID id,String email,String displayName,String status,String role,boolean verified,java.time.Instant createdAt){} public record AdminReportDto(UUID id,UUID reporterId,UUID reportedId,String reason,String details,String status,java.time.Instant createdAt){} public record AuditDto(UUID id,String actorEmail,String action,String targetType,String targetId,String details,java.time.Instant createdAt){}
 @Transactional(readOnly=true) public List<AdminUserDto> users(){return users.findAll().stream().sorted(Comparator.comparing(User::getCreatedAt).reversed()).map(u->new AdminUserDto(u.getId(),u.getEmail(),profiles.findByUserId(u.getId()).map(Profile::getDisplayName).orElse(""),u.getStatus().name(),u.getRole().name(),u.isEmailVerified(),u.getCreatedAt())).toList();}
 @Transactional public AdminUserDto status(UUID id,UserStatus status){var u=users.findById(id).orElseThrow(()->new NotFoundException("User not found"));u.setStatus(status);log("USER_STATUS_CHANGED","USER",id.toString(),"status="+status);return new AdminUserDto(u.getId(),u.getEmail(),profiles.findByUserId(u.getId()).map(Profile::getDisplayName).orElse(""),u.getStatus().name(),u.getRole().name(),u.isEmailVerified(),u.getCreatedAt());}
 @Transactional(readOnly=true) public List<AdminReportDto> reports(){return reports.findAll().stream().sorted(Comparator.comparing(Report::getCreatedAt).reversed()).map(this::dto).toList();}
 @Transactional public AdminReportDto reportStatus(UUID id,ReportStatus status){var r=reports.findById(id).orElseThrow(()->new NotFoundException("Report not found"));r.setStatus(status);log("REPORT_STATUS_CHANGED","REPORT",id.toString(),"status="+status);return dto(r);}
 @Transactional(readOnly=true) public List<AuditDto> audits(){return audits.findTop100ByOrderByCreatedAtDesc().stream().map(a->new AuditDto(a.getId(),a.getActor()==null?"system":a.getActor().getEmail(),a.getAction(),a.getTargetType(),a.getTargetId(),a.getDetails(),a.getCreatedAt())).toList();}
 private void log(String action,String type,String id,String details){audits.save(AuditLog.builder().actor(current.entity()).action(action).targetType(type).targetId(id).details(details).build());} private AdminReportDto dto(Report r){return new AdminReportDto(r.getId(),r.getReporter().getId(),r.getReported().getId(),r.getReason(),r.getDetails(),r.getStatus().name(),r.getCreatedAt());}
}
