package com.soulsync.service;
import com.soulsync.domain.*; import com.soulsync.domain.Enums.*; import com.soulsync.exception.*; import com.soulsync.repository.*; import com.soulsync.security.CurrentUser; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.PageRequest; import org.springframework.messaging.simp.SimpMessagingTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor
public class ChatService { private final ConversationRepository conversations; private final MessageRepository messages; private final UserRepository users; private final ProfileRepository profiles; private final BlockRepository blocks; private final ConnectionService connections; private final NotificationRepository notifications; private final CurrentUser current; private final SimpMessagingTemplate ws;
 public record ConversationDto(UUID id,UUID otherUserId,String otherDisplayName,Instant updatedAt){} public record MessageDto(UUID id,UUID conversationId,UUID senderId,String body,MessageType type,MessageStatus status,Instant createdAt,Instant readAt){}
 @Transactional public ConversationDto open(UUID targetId){ requirePhoneVerified(); UUID me=current.id();if(me.equals(targetId))throw new BadRequestException("Cannot chat with yourself");if(blocks.existsByBlockerIdAndBlockedId(me,targetId)||blocks.existsByBlockerIdAndBlockedId(targetId,me))throw new ForbiddenException("Conversation unavailable");if(!connections.connected(me,targetId))throw new ForbiddenException("Chat becomes available after an interest is accepted");var a=me.toString().compareTo(targetId.toString())<0?me:targetId;var b=a.equals(me)?targetId:me;var c=conversations.findByUser1IdAndUser2Id(a,b).orElseGet(()->conversations.save(Conversation.builder().user1(user(a)).user2(user(b)).build()));return dto(c,me);}
 @Transactional(readOnly=true) public List<ConversationDto> list(){UUID me=current.id();return conversations.findForUser(me).stream().map(c->dto(c,me)).toList();}
 @Transactional(readOnly=true) public List<MessageDto> messages(UUID conversationId,int page,int size){var c=conversation(conversationId);authorize(c);return messages.findByConversationIdOrderByCreatedAtDesc(conversationId,PageRequest.of(Math.max(0,page),Math.min(Math.max(1,size),100))).stream().map(this::dto).toList();}
 @Transactional public MessageDto send(UUID conversationId,String body){requirePhoneVerified();if(body==null||body.isBlank())throw new BadRequestException("Message cannot be empty");if(body.length()>4000)throw new BadRequestException("Message is too long");var c=conversation(conversationId);UUID me=current.id();authorize(c);UUID other=c.getUser1().getId().equals(me)?c.getUser2().getId():c.getUser1().getId();if(blocks.existsByBlockerIdAndBlockedId(me,other)||blocks.existsByBlockerIdAndBlockedId(other,me))throw new ForbiddenException("Conversation unavailable");var m=messages.save(Message.builder().conversation(c).sender(current.entity()).body(body.trim()).build());c.setUpdatedAt(Instant.now());var out=dto(m);notifications.save(Notification.builder().user(user(other)).type(NotificationType.MESSAGE).title("New message").body("You have a new message on SoulSync.").build());ws.convertAndSendToUser(me.toString(),"/queue/messages",out);ws.convertAndSendToUser(other.toString(),"/queue/messages",out);return out;}
 @Transactional public void markRead(UUID conversationId){var c=conversation(conversationId);authorize(c);UUID me=current.id();var page=messages.findByConversationIdOrderByCreatedAtDesc(conversationId,PageRequest.of(0,100));page.forEach(m->{if(!m.getSender().getId().equals(me)&&m.getStatus()!=MessageStatus.READ){m.setStatus(MessageStatus.READ);m.setReadAt(Instant.now());}});}
 private void requirePhoneVerified(){if(!current.entity().isPhoneVerified())throw new ForbiddenException("Verify your phone number before using chat");} private Conversation conversation(UUID id){return conversations.findById(id).orElseThrow(()->new NotFoundException("Conversation not found"));} private void authorize(Conversation c){UUID me=current.id();if(!c.getUser1().getId().equals(me)&&!c.getUser2().getId().equals(me))throw new ForbiddenException("Conversation unavailable");} private User user(UUID id){return users.findById(id).orElseThrow(()->new NotFoundException("User not found"));}
 private ConversationDto dto(Conversation c,UUID me){var o=c.getUser1().getId().equals(me)?c.getUser2():c.getUser1();String name=profiles.findByUserId(o.getId()).map(Profile::getDisplayName).orElse("SoulSync member");return new ConversationDto(c.getId(),o.getId(),name,c.getUpdatedAt());}
 private MessageDto dto(Message m){return new MessageDto(m.getId(),m.getConversation().getId(),m.getSender().getId(),m.getBody(),m.getType(),m.getStatus(),m.getCreatedAt(),m.getReadAt());}
}
