package com.soulsync.service;

import com.soulsync.domain.*; import com.soulsync.domain.Enums.*; import com.soulsync.exception.*; import com.soulsync.repository.*; import com.soulsync.security.CurrentUser; import com.soulsync.web.dto.ProfileDtos.*;
import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import jakarta.persistence.criteria.Predicate; import java.time.*; import java.util.*;

@Service @RequiredArgsConstructor
public class ProfileService {
 private final ProfileRepository profiles; private final ProfilePhotoRepository photos; private final PartnerPreferenceRepository preferences; private final ProfileViewRepository views; private final BlockRepository blocks; private final CurrentUser current;
 @Transactional(readOnly=true) public ProfileDetail me(){ return detail(current.id(),true); }
 @Transactional public ProfileDetail update(ProfileUpdate r){ var p=profiles.findByUserId(current.id()).orElseThrow(()->new NotFoundException("Profile not found")); p.setDisplayName(r.displayName().trim()); p.setDateOfBirth(r.dateOfBirth()); p.setGender(clean(r.gender())); p.setHeightCm(r.heightCm()); p.setMaritalStatus(clean(r.maritalStatus())); p.setMotherTongue(clean(r.motherTongue())); p.setReligion(clean(r.religion())); p.setCommunity(clean(r.community())); p.setCountry(clean(r.country())); p.setState(clean(r.state())); p.setCity(clean(r.city())); p.setEducation(clean(r.education())); p.setOccupation(clean(r.occupation())); p.setIncomeRange(clean(r.incomeRange())); p.setDiet(clean(r.diet())); p.setSmoking(clean(r.smoking())); p.setDrinking(clean(r.drinking())); p.setAbout(clean(r.about())); p.setProfileCreatedBy(clean(r.profileCreatedBy())); if(r.visibility()!=null)p.setVisibility(r.visibility()); p.setCompletionPercent(completion(p)); p.setLastActiveAt(Instant.now()); return detail(p.getUser().getId(),true); }
 @Transactional public ProfileDetail get(UUID userId){ var me=current.id(); if(me.equals(userId))return detail(userId,true); if(blocks.existsByBlockerIdAndBlockedId(me,userId)||blocks.existsByBlockerIdAndBlockedId(userId,me)) throw new NotFoundException("Profile not found"); var target=profiles.findByUserId(userId).orElseThrow(()->new NotFoundException("Profile not found")); if(target.getVisibility()==ProfileVisibility.HIDDEN) throw new NotFoundException("Profile not found"); views.save(ProfileView.builder().viewer(current.entity()).viewed(target.getUser()).build()); return detail(userId,false); }
 @Transactional(readOnly=true) public Page<ProfileCard> search(SearchFilter f,int page,int size){ size=Math.min(Math.max(size,1),50); var me=current.id(); var blocked=blockedIds(me); Specification<Profile> spec=(root,q,cb)->{ List<Predicate> ps=new ArrayList<>(); ps.add(cb.notEqual(root.get("user").get("id"),me)); ps.add(cb.notEqual(root.get("visibility"),ProfileVisibility.HIDDEN)); ps.add(cb.equal(root.get("user").get("status"),UserStatus.ACTIVE)); if(!blocked.isEmpty())ps.add(root.get("user").get("id").in(blocked).not()); eq(cb,ps,root.get("gender"),f.gender()); eq(cb,ps,root.get("country"),f.country()); eq(cb,ps,root.get("state"),f.state()); eq(cb,ps,root.get("city"),f.city()); eq(cb,ps,root.get("religion"),f.religion()); eq(cb,ps,root.get("motherTongue"),f.motherTongue()); like(cb,ps,root.get("education"),f.education()); like(cb,ps,root.get("occupation"),f.occupation()); if(f.minHeightCm()!=null)ps.add(cb.greaterThanOrEqualTo(root.get("heightCm"),f.minHeightCm())); if(f.maxHeightCm()!=null)ps.add(cb.lessThanOrEqualTo(root.get("heightCm"),f.maxHeightCm())); if(f.minAge()!=null){ var latest=LocalDate.now().minusYears(f.minAge()); ps.add(cb.lessThanOrEqualTo(root.get("dateOfBirth"),latest)); } if(f.maxAge()!=null){ var earliest=LocalDate.now().minusYears(f.maxAge()+1L).plusDays(1); ps.add(cb.greaterThanOrEqualTo(root.get("dateOfBirth"),earliest)); } var activeBoost = cb.<Integer>selectCase()
        .when(
            cb.greaterThan(
                root.<Instant>get("boostedUntil"),
                Instant.now()
            ),
            0
        )
        .otherwise(1);
      q.orderBy(
          cb.asc(activeBoost),
          cb.desc(root.get("lastActiveAt"))
      );
      return cb.and(ps.toArray(Predicate[]::new)); };
   var pref=preferences.findByUserId(me).orElse(null); return profiles.findAll(spec,PageRequest.of(Math.max(page,0),size)).map(p->card(p,pref)); }
 @Transactional(readOnly=true) public List<ProfileCard> recommendations(){ var pref=preferences.findByUserId(current.id()).orElseThrow(); var all=search(new SearchFilter(pref.getMinAge(),pref.getMaxAge(),null,pref.getCountry(),pref.getState(),null,pref.getReligion(),pref.getMotherTongue(),pref.getEducation(),pref.getOccupation(),pref.getMinHeightCm(),pref.getMaxHeightCm()),0,40).getContent(); return all.stream().sorted(Comparator.comparing(ProfileCard::boosted).reversed().thenComparing(Comparator.comparing((ProfileCard c)->Optional.ofNullable(c.matchScore()).orElse(0)).reversed())).limit(20).toList(); }
 @Transactional(readOnly=true) public PreferenceDto preference(){ return prefDto(preferences.findByUserId(current.id()).orElseThrow(()->new NotFoundException("Preferences not found"))); }
 @Transactional public PreferenceDto updatePreference(PreferenceUpdate r){ if(r.minAge()!=null&&r.maxAge()!=null&&r.minAge()>r.maxAge())throw new BadRequestException("minAge cannot exceed maxAge"); var p=preferences.findByUserId(current.id()).orElseThrow(); p.setMinAge(r.minAge());p.setMaxAge(r.maxAge());p.setMinHeightCm(r.minHeightCm());p.setMaxHeightCm(r.maxHeightCm());p.setCountry(clean(r.country()));p.setState(clean(r.state()));p.setReligion(clean(r.religion()));p.setMotherTongue(clean(r.motherTongue()));p.setEducation(clean(r.education()));p.setOccupation(clean(r.occupation()));p.setDiet(clean(r.diet())); return prefDto(p); }
 private ProfileDetail detail(UUID userId,boolean owner){ var p=profiles.findByUserId(userId).orElseThrow(()->new NotFoundException("Profile not found")); var photoDtos=photos.findByUserIdOrderBySortOrderAsc(userId).stream().filter(x->owner||x.getVisibility()==PhotoVisibility.PUBLIC).map(x->new PhotoDto(x.getId(),x.getUrl(),x.getSortOrder(),x.isPrimary(),x.getVisibility())).toList(); return new ProfileDetail(userId,p.getDisplayName(),p.getDateOfBirth(),age(p.getDateOfBirth()),p.getGender(),p.getHeightCm(),p.getMaritalStatus(),p.getMotherTongue(),p.getReligion(),p.getCommunity(),p.getCountry(),p.getState(),p.getCity(),p.getEducation(),p.getOccupation(),owner?p.getIncomeRange():null,p.getDiet(),p.getSmoking(),p.getDrinking(),p.getAbout(),p.getProfileCreatedBy(),p.getVisibility(),p.getCompletionPercent(),p.getLastActiveAt(),photoDtos,p.getUser().isEmailVerified()); }
 private ProfileCard card(Profile p,PartnerPreference pref){ var primary=photos.findByUserIdOrderBySortOrderAsc(p.getUser().getId()).stream().filter(ProfilePhoto::isPrimary).findFirst().or(()->photos.findByUserIdOrderBySortOrderAsc(p.getUser().getId()).stream().findFirst()).map(ProfilePhoto::getUrl).orElse(null); return new ProfileCard(p.getUser().getId(),p.getDisplayName(),age(p.getDateOfBirth()),p.getGender(),p.getHeightCm(),p.getCity(),p.getState(),p.getCountry(),p.getReligion(),p.getMotherTongue(),p.getEducation(),p.getOccupation(),primary,score(p,pref),p.getLastActiveAt(),p.getUser().isEmailVerified(),p.getBoostedUntil()!=null&&p.getBoostedUntil().isAfter(Instant.now())); }
 private int score(Profile p,PartnerPreference f){ if(f==null)return 0; int total=0,max=0; max+=20; if(inAge(age(p.getDateOfBirth()),f.getMinAge(),f.getMaxAge()))total+=20; max+=10;if(inRange(p.getHeightCm(),f.getMinHeightCm(),f.getMaxHeightCm()))total+=10; total+=match(p.getCountry(),f.getCountry(),15);max+=15; total+=match(p.getState(),f.getState(),10);max+=10; total+=match(p.getReligion(),f.getReligion(),15);max+=15; total+=match(p.getMotherTongue(),f.getMotherTongue(),10);max+=10; total+=contains(p.getEducation(),f.getEducation(),10);max+=10; total+=contains(p.getOccupation(),f.getOccupation(),5);max+=5; total+=match(p.getDiet(),f.getDiet(),5);max+=5; return max==0?0:(int)Math.round(total*100.0/max); }
 private static int match(String a,String b,int w){return b==null||b.isBlank()?w/2:(a!=null&&a.equalsIgnoreCase(b)?w:0);} private static int contains(String a,String b,int w){return b==null||b.isBlank()?w/2:(a!=null&&a.toLowerCase().contains(b.toLowerCase())?w:0);} private static boolean inAge(Integer a,Integer min,Integer max){return a!=null&&(min==null||a>=min)&&(max==null||a<=max);} private static boolean inRange(Integer a,Integer min,Integer max){return a!=null&&(min==null||a>=min)&&(max==null||a<=max);} private static Integer age(LocalDate d){return d==null?null:Period.between(d,LocalDate.now()).getYears();}
 private Set<UUID> blockedIds(UUID me){ Set<UUID>s=new HashSet<>(); blocks.findByBlockerId(me).forEach(b->s.add(b.getBlocked().getId())); blocks.findByBlockedId(me).forEach(b->s.add(b.getBlocker().getId())); return s; }
 private static void eq(jakarta.persistence.criteria.CriteriaBuilder cb,List<Predicate> ps,jakarta.persistence.criteria.Path<String> p,String v){if(v!=null&&!v.isBlank())ps.add(cb.equal(cb.lower(p),v.trim().toLowerCase()));} private static void like(jakarta.persistence.criteria.CriteriaBuilder cb,List<Predicate> ps,jakarta.persistence.criteria.Path<String> p,String v){if(v!=null&&!v.isBlank())ps.add(cb.like(cb.lower(p),"%"+v.trim().toLowerCase()+"%"));}
 private static String clean(String s){return s==null?null:(s.isBlank()?null:s.trim());}
 private int completion(Profile p){ int n=1,total=18; Object[] v={p.getDateOfBirth(),p.getGender(),p.getHeightCm(),p.getMaritalStatus(),p.getMotherTongue(),p.getReligion(),p.getCommunity(),p.getCountry(),p.getState(),p.getCity(),p.getEducation(),p.getOccupation(),p.getIncomeRange(),p.getDiet(),p.getSmoking(),p.getDrinking(),p.getAbout()}; for(Object x:v)if(x!=null&&(!(x instanceof String s)||!s.isBlank()))n++; return (int)Math.round(n*100.0/total); }
 private PreferenceDto prefDto(PartnerPreference p){return new PreferenceDto(p.getMinAge(),p.getMaxAge(),p.getMinHeightCm(),p.getMaxHeightCm(),p.getCountry(),p.getState(),p.getReligion(),p.getMotherTongue(),p.getEducation(),p.getOccupation(),p.getDiet());}
}
