package com.soulsync.service;
import com.fasterxml.jackson.databind.*; import com.soulsync.domain.*; import com.soulsync.domain.Enums.Plan; import com.soulsync.exception.*; import com.soulsync.repository.SubscriptionRepository; import com.soulsync.security.CurrentUser; import lombok.RequiredArgsConstructor; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import javax.crypto.Mac; import java.security.MessageDigest; import javax.crypto.spec.SecretKeySpec; import java.net.URI; import java.net.http.*; import java.net.URLEncoder; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import java.util.stream.Collectors;
@Service @RequiredArgsConstructor
public class SubscriptionService { private final SubscriptionRepository repo; private final CurrentUser current; private final ObjectMapper json;
 @Value("${soulsync.dev-mode}") boolean devMode; @Value("${soulsync.frontend-url}") String frontend; @Value("${STRIPE_SECRET_KEY:}") String stripeSecret; @Value("${STRIPE_WEBHOOK_SECRET:}") String webhookSecret; @Value("${STRIPE_PRICE_PREMIUM:}") String premiumPrice; @Value("${STRIPE_PRICE_PREMIUM_PLUS:}") String plusPrice;
 public record SubscriptionDto(String plan,Instant startsAt,Instant endsAt,Set<String> entitlements){} public record CheckoutDto(String id,String url){}
 @Transactional(readOnly=true) public SubscriptionDto mine(){return dto(repo.findByUserId(current.id()).orElseThrow());}
 @Transactional public SubscriptionDto devSet(Plan plan){if(!devMode)throw new ForbiddenException("Development plan switching is disabled");var s=repo.findByUserId(current.id()).orElseThrow();s.setPlan(plan);s.setStartsAt(Instant.now());s.setEndsAt(plan==Plan.FREE?null:Instant.now().plus(30,java.time.temporal.ChronoUnit.DAYS));return dto(s);}
 public CheckoutDto checkout(Plan plan){if(plan==Plan.FREE)throw new BadRequestException("Choose a paid plan");if(stripeSecret.isBlank())throw new BadRequestException("Stripe is not configured");String price=plan==Plan.PREMIUM?premiumPrice:plusPrice;if(price==null||price.isBlank())throw new BadRequestException("Stripe price ID is not configured");var data=new LinkedHashMap<String,String>();data.put("mode","subscription");data.put("line_items[0][price]",price);data.put("line_items[0][quantity]","1");data.put("success_url",frontend+"/premium?success=1");data.put("cancel_url",frontend+"/premium?canceled=1");data.put("client_reference_id",current.id().toString());data.put("metadata[user_id]",current.id().toString());data.put("metadata[plan]",plan.name());String form=data.entrySet().stream().map(e->enc(e.getKey())+"="+enc(e.getValue())).collect(Collectors.joining("&"));try{var req=HttpRequest.newBuilder(URI.create("https://api.stripe.com/v1/checkout/sessions")).header("Authorization","Bearer "+stripeSecret).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(form)).build();var res=HttpClient.newHttpClient().send(req,HttpResponse.BodyHandlers.ofString());if(res.statusCode()/100!=2)throw new BadRequestException("Stripe checkout could not be created");var n=json.readTree(res.body());return new CheckoutDto(n.path("id").asText(),n.path("url").asText());}catch(BadRequestException e){throw e;}catch(Exception e){throw new BadRequestException("Stripe checkout failed");}}
 @Transactional public void webhook(String payload,String signature){verify(payload,signature);try{JsonNode event=json.readTree(payload);String type=event.path("type").asText();JsonNode obj=event.path("data").path("object");if("checkout.session.completed".equals(type)){UUID uid=UUID.fromString(obj.path("client_reference_id").asText());Plan plan=Plan.valueOf(obj.path("metadata").path("plan").asText());var s=repo.findByUserId(uid).orElseThrow();s.setPlan(plan);s.setStartsAt(Instant.now());s.setProviderCustomerId(obj.path("customer").asText(null));s.setProviderSubscriptionId(obj.path("subscription").asText(null));}else if("customer.subscription.deleted".equals(type)){String sid=obj.path("id").asText();repo.findAll().stream().filter(s->sid.equals(s.getProviderSubscriptionId())).findFirst().ifPresent(s->{s.setPlan(Plan.FREE);s.setEndsAt(Instant.now());s.setProviderSubscriptionId(null);});}}catch(Exception e){throw new BadRequestException("Invalid Stripe webhook payload");}}
 private void verify(String payload,String header){if(webhookSecret.isBlank())throw new BadRequestException("Stripe webhook is not configured");try{Map<String,String> p=Arrays.stream(Optional.ofNullable(header).orElse("").split(",")).map(x->x.split("=",2)).filter(x->x.length==2).collect(Collectors.toMap(x->x[0],x->x[1],(a,b)->a));long t=Long.parseLong(p.getOrDefault("t","0"));if(Math.abs(Instant.now().getEpochSecond()-t)>300)throw new SecurityException();String signed=t+"."+payload;Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(webhookSecret.getBytes(StandardCharsets.UTF_8),"HmacSHA256"));String expected=java.util.HexFormat.of().formatHex(mac.doFinal(signed.getBytes(StandardCharsets.UTF_8)));if(!MessageDigest.isEqual(expected.getBytes(StandardCharsets.UTF_8),p.getOrDefault("v1","").getBytes(StandardCharsets.UTF_8)))throw new SecurityException();}catch(Exception e){throw new BadRequestException("Invalid Stripe signature");}}
 private SubscriptionDto dto(Subscription s){Set<String> e=new LinkedHashSet<>(Set.of("SEND_INTEREST","BASIC_SEARCH"));if(s.getPlan()!=Plan.FREE)e.addAll(Set.of("UNLIMITED_INTERESTS","ADVANCED_SEARCH","VIEW_PROFILE_VISITORS","MESSAGE_CONNECTIONS","VIEW_CONTACT","ENHANCED_DISCOVERY"));if(s.getPlan()==Plan.PREMIUM_PLUS)e.addAll(Set.of("PROFILE_BOOST","VIDEO_CALL","PRIORITY_SUPPORT"));return new SubscriptionDto(s.getPlan().name(),s.getStartsAt(),s.getEndsAt(),e);} private static String enc(String s){return URLEncoder.encode(s,StandardCharsets.UTF_8);}
}
