export const API_BASE=process.env.NEXT_PUBLIC_API_URL??"/api/v1";
export const BACKEND_ORIGIN=API_BASE.replace(/\/api\/v1\/?$/,'');
export type ApiOptions=RequestInit&{auth?:boolean};
export function getAccessToken(){return typeof window==='undefined'?null:localStorage.getItem('soulsync_access');}
export function setTokens(access:string,refresh:string){localStorage.setItem('soulsync_access',access);localStorage.setItem('soulsync_refresh',refresh);}
export function clearTokens(){localStorage.removeItem('soulsync_access');localStorage.removeItem('soulsync_refresh');}
async function raw(path:string,options:ApiOptions={}){const headers=new Headers(options.headers);if(options.body&&!headers.has('Content-Type')&&!(options.body instanceof FormData))headers.set('Content-Type','application/json');if(options.auth!==false){const t=getAccessToken();if(t)headers.set('Authorization',`Bearer ${t}`);}const url=path.startsWith('/api/v1/')?`${BACKEND_ORIGIN}${path}`:`${API_BASE}${path}`;return fetch(url,{...options,headers,cache:'no-store'});}
export async function api<T=unknown>(path:string,options:ApiOptions={}):Promise<T>{let res=await raw(path,options);if(res.status===401&&options.auth!==false){const refresh=localStorage.getItem('soulsync_refresh');if(refresh){const rr=await raw('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken:refresh}),auth:false});if(rr.ok){const p=await rr.json();setTokens(p.accessToken,p.refreshToken);res=await raw(path,options);}else clearTokens();}}if(!res.ok){let message=`Request failed (${res.status})`;try{const e=await res.json();message=e.message??message;if(e.fields)message+=`: ${Object.values(e.fields).join(', ')}`;}catch{}throw new Error(message);}if(res.status===204)return undefined as T;const text=await res.text();return(text?JSON.parse(text):undefined) as T;}

export async function apiBlob(path:string):Promise<Blob>{let res=await raw(path,{});if(res.status===401){const refresh=localStorage.getItem('soulsync_refresh');if(refresh){const rr=await raw('/auth/refresh',{method:'POST',body:JSON.stringify({refreshToken:refresh}),auth:false});if(rr.ok){const p=await rr.json();setTokens(p.accessToken,p.refreshToken);res=await raw(path,{})}}}if(!res.ok)throw new Error(`Image request failed (${res.status})`);return res.blob();}
export function photoUrl(path?:string){if(!path)return undefined;return path.startsWith('http')?path:`${BACKEND_ORIGIN}${path}`;}
export async function logout(){const refresh=localStorage.getItem('soulsync_refresh');if(refresh)try{await api('/auth/logout',{method:'POST',body:JSON.stringify({refreshToken:refresh}),auth:false});}catch{}clearTokens();window.location.href='/login';}
